callsign=AK7AN
module=A
port=9000
peertimeout=60
debug_output_port=9001
ysf_frame_mode=network


# Timers
idle_timeout_ms=15000
max_tx_ms=180000




# Protocol Enable/Disable
dstar_enabled=1
ysf_enabled=1
dmr_enabled=1

# Protocol Ports
dstar_port=9000
ysf_port=9001
dmr_port=9002
