callsign=AK7AN
module=A
port=9000
peertimeout=60
debug_output_port=9101
ysf_frame_mode=network


# Timers
idle_timeout_ms=15000
max_tx_ms=180000




# Protocol Enable/Disable
dstar_enabled=1
ysf_enabled=1
dmr_enabled=1

# Protocol Ports
dstar_port=9000
ysf_port=9001
dmr_port=9002

# XLXD Peering
xlxd_peering_enabled=1
xlxd_peer_reflector=XLX999
xlxd_peer_host=127.0.0.1
xlxd_peer_port=10001
xlxd_peer_module=A

# XLXD Peer Keepalive
xlxd_peer_poll_interval_ms=30000
xlxd_peer_timeout_ms=90000

# Future Protocol Enable/Disable
nxdn_enabled=1
p25_enabled=0
m17_enabled=0

#
# Routing Policy
#

route_source_reflector=XLX999
route_source_module=A

route_enable_ysf=1
route_enable_dmr=1
route_enable_nxdn=0
route_enable_p25=0
route_enable_m17=0






#
# AMBE Devices
#

ambe_decode_device=/dev/serial/by-id/usb-NW_Digital_Radio_09_25_ThumbDV_D30G37BA-if00-port0
ambe_encode_device=/dev/serial/by-id/usb-NW_Digital_Radio_09_25_ThumbDV_D30G37AJ-if00-port0
ambe_baud=460800


#
# Audio Levels
#

audio_dstar_gain_in=16
audio_dstar_gain_out=-10

audio_ysf_gain_in=-3
audio_ysf_gain_out=0

audio_dmr_gain_in=-3
audio_dmr_gain_out=0

audio_nxdn_gain_in=0
audio_nxdn_gain_out=0

audio_p25_gain_in=0
audio_p25_gain_out=0

audio_m17_gain_in=0
audio_m17_gain_out=0
